import images from './images';

const wines = [
  {
    title: 'Chapel Hill Shiraz',
    price: '$56',
    tags: 'AU | Bottle',
  },
  {
    title: 'Catena Malbee',
    price: '$59',
    tags: 'AU | Bottle',
  },
  {
    title: 'La Vieillw Rose',
    price: '$44',
    tags: 'FR | 750 ml',
  },
  {
    title: 'Rhino Pale Ale',
    price: '$31',
    tags: 'CA | 750 ml',
  },
  {
    title: 'Irish Guinness',
    price: '$26',
    tags: 'IE | 750 ml',
  },
];

const cocktails = [
  {
    title: 'Aperol Sprtiz',
    price: '$20',
    tags: 'Aperol | Villa Marchesi prosecco | soda | 30 ml',
  },
  {
    title: "Dark 'N' Stormy",
    price: '$16',
    tags: 'Dark rum | Ginger beer | Slice of lime',
  },
  {
    title: 'Daiquiri',
    price: '$10',
    tags: 'Rum | Citrus juice | Sugar',
  },
  {
    title: 'Old Fashioned',
    price: '$31',
    tags: 'Bourbon | Brown sugar | Angostura Bitters',
  },
  {
    title: 'Negroni',
    price: '$26',
    tags: 'Gin | Sweet Vermouth | Campari | Orange garnish',
  },
];
const awards = [ 
  {
    imgUrl: images.award02,
    title: 'Bib Gourmond',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
  },
  {
    imgUrl: images.award01,
    title: 'Rising Star',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
  },
  {
    imgUrl: images.award05,
    title: 'AA Hospitality',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
  },
  {
    imgUrl: images.award03,
    title: 'Outstanding Chef',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
  },
];
const menu = [
  {
    id: 1,
    title: 'Belgian Waffle',
    category: 'breakfast',
    price: 7.50,
    img: './images/R.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 2,
    title: 'Burger',
    category: 'lunch',
    price: 3.50,
    img: './images/item-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 3,
    title: 'Chocolate milkshake',
    category: 'drinks',
    price: 4.00,
    img: './images/a.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 7.00,
    img: './images/item-4.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 3.00,
    img: './images/item-5.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'drinks',
    price: 5.00,
    img: './images/item-6.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 7,
    title: 'Bacon Burger',
    category: 'breakfast',
    price: 4.00,
    img: './images/item-7.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 5.00,
    img: './images/item-8.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 9,
    title: 'Pink Milkshake',
    category: 'drinks',
    price: 3.00,
    img: './images/p.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 10,
    title: 'Rasberry Cocktail',
    category: 'drinks',
    price: 4.00,
    img: './images/ras.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 11,
    title: 'Negroni',
    category: 'drinks',
    price: 3.00,
    img: './images/n.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 12,
    title: 'English Breakfast',
    category: 'breakfast',
    price: 9.00,
    img: './images/e.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 13,
    title: 'French Toast',
    category: 'breakfast',
    price: 6.00,
    img: './images/f.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 14,
    title: 'Pancakes',
    category: 'breakfast',
    price: 8.00,
    img: './images/pp.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 15,
    title: 'Sliced Duck',
    category: 'lunch',
    price: 8.00,
    img: './images/s.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 16,
    title: 'Duck Leg',
    category: 'lunch',
    price: 7.00,
    img: './images/dd.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 17,
    title: 'Grilled Bread',
    category: 'lunch',
    price: 5.00,
    img: './images/bg.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 18,
    title: 'Black Tortuga',
    category: 'drinks',
    price: 5.00,
    img: './images/bt.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 19,
    title: 'Steak',
    category: 'dinner',
    price: 22.00,
    img: './images/st.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 20,
    title: 'Chicken Pasta',
    category: 'dinner',
    price: 9.00,
    img: './images/pc.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 21,
    title: 'Risotto',
    category: 'dinner',
    price: 7.00,
    img: './images/rr.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 22,
    title: 'Spaghetti with Meat Sauce',
    category: 'dinner',
    price: 8.00,
    img: './images/sm.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 23,
    title: 'Vegan Pizza',
    category: 'dinner',
    price: 10.00,
    img: './images/pz.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 24,
    title: 'Salmon',
    category: 'dinner',
    price: 12.00,
    img: './images/sl.png',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
];

export default { wines, cocktails, awards, menu };
